ALTER TABLE products
ALTER COLUMN name TYPE VARCHAR(255);

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS code VARCHAR(50);

UPDATE products
SET code = 'PROD-' || id
WHERE code IS NULL;

ALTER TABLE products
    ALTER COLUMN code SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_products_code
    ON products(code);

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS units_per_box INTEGER NOT NULL DEFAULT 1;

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW();